In [1]:
%pip install pandas numpy matplotlib seaborn

 



Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

a = np.array([[[1,2,3,4],
              [6,7,8,2],
              [9,0,1,2]],
             [[9,4,6,2],
              [1,1,1,1],
              [1,1,1,1],
             ]])
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)


(2, 3, 4)
3
24
int64


In [3]:
import numpy as np

a = np.array([[1,2,3],
             [4,"Hello",6],
            [7,8,9]])
print(a[0][0])



1


In [4]:
import numpy as np

a = np.full((2,3,4), 9)
print(a)

a = np.zeros((2,3,1))
print(a)

a = np.ones((2,3,4))
print(a)


[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]
[[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [5]:
import numpy as np

a = np.empty((5,5,5))
print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [6]:
 import numpy as np

x = np.arange(0, 50, 2)
print(x)

x = np.linspace(0, 1000, 5)
print(x)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
[   0.  250.  500.  750. 1000.]


In [7]:
import numpy as np

print(np.nan)
print(np.inf) 

nan
inf


In [8]:
import numpy as np

l1 = [1,2,3,4]
l2 = [5,6,7,8]

a1 = np.array(l1)
a2 = np.array(l2)

print(l1 * 5)
print(a1 * 5)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
[ 5 10 15 20]


In [9]:
import numpy as np

a1 = np.array([1,2,3])
a2 = np.array([[1],
               [2]])
print(a1 + a2)

#forms a matrix like addition (multiplication)

[[2 3 4]
 [3 4 5]]


In [10]:
import numpy as np

a = np.array([[1,2,3], [4,5,5]])

print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.23606798]]


In [11]:
import numpy as np

a = np.array([1,2,3])

a = np.append(a, [7,8,9])
a = np.insert(a, 3, [4,5,6])

print(a)

[1 2 3 4 5 6 7 8 9]
